defaultPortal: project
portals:
  - name: project
    portalId: 19944133
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CIXAjYucLxIIAA0ADAAA4AEYxaXBCSCcke4DKO7pDDIZAHJ2sWQ9ruR78khYw0IJhzbWaTEbkJBdITooAAAEQQAAAHgAAAAAAAAAAIABAAAAAAAEwADAB2D-_zEAAAAAAAAAYEIZAHJ2sWRn0swc7tvM3agVbt4XwZ_LjD4PdkoDbmEx
        expiresAt: '2021-05-31T07:46:25.929Z'
    personalAccessKey: >-
      CiRkNWRmOWUwYS1hODQ1LTRlNmItYTJmNy0wNDQ4ZjQ2NGRiNjMQxaXBCRicke4DKhkABeaRgr373wTs9NBakqbs4uab1zGfWdn7SgNuYTE
