defaultPortal: project
portals:
  - name: project
    portalId: 19944133
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CMTV2PWcLxIIAA0ADAAA4AEYxaXBCSCcke4DKO7pDDIZAPYiTK5dS4oo0dvajkkvKA-UrqMwSUKtnTooAAAEQQAAAHgAAAAAAAAAAIABAAAAAAAEwADAB2D-_zEAAAAAAAAAYEIZAPYiTK644A8J57Bxwij2boJxLxtKOeFslUoDbmEx
        expiresAt: '2021-06-02T21:51:55.599Z'
    personalAccessKey: >-
      CiRkNWRmOWUwYS1hODQ1LTRlNmItYTJmNy0wNDQ4ZjQ2NGRiNjMQxaXBCRicke4DKhkABeaRgr373wTs9NBakqbs4uab1zGfWdn7SgNuYTE
