defaultPortal: project
portals:
  - name: project
    portalId: 19944133
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CJ_mua-dLxIIAA0ADAAA4AEYxaXBCSCcke4DKO7pDDIZAGsJY08fnAYk5gBO1wJhSK0SihQPTN0YhzooAAAEQQAAAHgAAAAAAAAAAIABAAAAAAAEwADAB2D-_zEAAAAAAAAAYEIZAGsJY0-yYey-ZnG46zHOVhFTz5rtI35aHUoDbmEx
        expiresAt: '2021-06-04T07:30:44.643Z'
    personalAccessKey: >-
      CiRkNWRmOWUwYS1hODQ1LTRlNmItYTJmNy0wNDQ4ZjQ2NGRiNjMQxaXBCRicke4DKhkABeaRgr373wTs9NBakqbs4uab1zGfWdn7SgNuYTE
